/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package developpement_swing;

import java.awt.*;
import java.awt.image.ImageObserver;
import java.text.AttributedCharacterIterator;
import javax.swing.*;

/**
 *
 * @author 80010-37-15
 */
public class Form extends javax.swing.JFrame {

    String result, old_world;

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Red_fond = new javax.swing.JRadioButton();
        Green_fond = new javax.swing.JRadioButton();
        Blue_fond = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        Red_text = new javax.swing.JRadioButton();
        Green_text = new javax.swing.JRadioButton();
        Black_text = new javax.swing.JRadioButton();
        Panel_casse = new javax.swing.JPanel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        Min = new javax.swing.JRadioButton();
        Maj = new javax.swing.JRadioButton();
        Choice_panel = new javax.swing.JPanel();
        Color_font = new javax.swing.JCheckBox();
        Color_text = new javax.swing.JCheckBox();
        Casse = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text_1 = new javax.swing.JTextPane();
        Text_2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 238, 238));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fond"));
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Red_fond.setText("Rouge");
        Red_fond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Red_fondActionPerformed(evt);
            }
        });

        Green_fond.setText("Vert");
        Green_fond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Green_fondActionPerformed(evt);
            }
        });

        Blue_fond.setText("Bleu");
        Blue_fond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blue_fondActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Red_fond)
                    .addComponent(Green_fond)
                    .addComponent(Blue_fond))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Red_fond)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Green_fond)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Blue_fond)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Fond"));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Red_text.setText("Rouge");
        Red_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Red_textActionPerformed(evt);
            }
        });

        Green_text.setText("Vert");
        Green_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Green_textActionPerformed(evt);
            }
        });

        Black_text.setText("Noir");
        Black_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Black_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Red_text)
                    .addComponent(Green_text)
                    .addComponent(Black_text))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Red_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Green_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Black_text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_casse.setBorder(javax.swing.BorderFactory.createTitledBorder("Fond"));
        Panel_casse.setForeground(new java.awt.Color(238, 238, 238));
        Panel_casse.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Panel_casseAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jRadioButton7.setText("jRadioButton1");

        jRadioButton8.setText("jRadioButton2");

        Min.setText("Minuscule");
        Min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinActionPerformed(evt);
            }
        });

        Maj.setText("Majuscule");
        Maj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_casseLayout = new javax.swing.GroupLayout(Panel_casse);
        Panel_casse.setLayout(Panel_casseLayout);
        Panel_casseLayout.setHorizontalGroup(
            Panel_casseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_casseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_casseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_casseLayout.createSequentialGroup()
                        .addGap(0, 116, Short.MAX_VALUE)
                        .addGroup(Panel_casseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton8, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(Panel_casseLayout.createSequentialGroup()
                        .addGroup(Panel_casseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Min)
                            .addComponent(Maj))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel_casseLayout.setVerticalGroup(
            Panel_casseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_casseLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Min)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Maj)
                .addGap(201, 201, 201)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Choice_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Choix"));
        Choice_panel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Choice_panelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Color_font.setText("Couleur du fond");
        Color_font.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Color_fontStateChanged(evt);
            }
        });
        Color_font.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Color_fontActionPerformed(evt);
            }
        });

        Color_text.setText("Couleur du texte");
        Color_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Color_textActionPerformed(evt);
            }
        });

        Casse.setText("Casse");
        Casse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Choice_panelLayout = new javax.swing.GroupLayout(Choice_panel);
        Choice_panel.setLayout(Choice_panelLayout);
        Choice_panelLayout.setHorizontalGroup(
            Choice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Choice_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Choice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Color_font)
                    .addComponent(Color_text)
                    .addComponent(Casse))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        Choice_panelLayout.setVerticalGroup(
            Choice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Choice_panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Color_font)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Color_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Casse)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setText("Tapez votre texte");

        Text_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Text_1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Text_1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Text_2.setBackground(new java.awt.Color(204, 0, 102));
        Text_2.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Text_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_casse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Choice_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Choice_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_casse, javax.swing.GroupLayout.PREFERRED_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Color_fontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Color_fontActionPerformed
        
    }//GEN-LAST:event_Color_fontActionPerformed

    private void MinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinActionPerformed
        old_world = Text_2.getText();
        if (Casse.isSelected()) {
            if (Min.isSelected()) {
                Maj.setSelected(false);
                result = Text_2.getText().toLowerCase();
                Text_2.setText(result);
            } else {
                Text_2.setText(old_world);
            }
        }
    }//GEN-LAST:event_MinActionPerformed

    private void MajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MajActionPerformed
        old_world = Text_2.getText();
        if (Casse.isSelected()) {
            if (Maj.isSelected()) {
                Min.setSelected(false);
                result = Text_2.getText().toUpperCase();
                Text_2.setText(result);
            } else {
                Text_2.setText(old_world);
            }
        }

    }//GEN-LAST:event_MajActionPerformed

    private void CasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasseActionPerformed
        if (Casse.isSelected()) {
            Panel_casse.setEnabled(true);
            Maj.setEnabled(true);
            Min.setEnabled(true);
        } else {
            Panel_casse.setEnabled(false);
            Maj.setEnabled(false);
            Min.setEnabled(false);
            Maj.setSelected(false);
            Min.setSelected(false);
        }

    }//GEN-LAST:event_CasseActionPerformed

    private void Color_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Color_textActionPerformed
        if (Color_text.isSelected()) {
            jPanel2.setEnabled(true);
            Red_text.setEnabled(true);
            Green_text.setEnabled(true);
            Black_text.setEnabled(true);
        } else {
            jPanel2.setEnabled(false);
            Red_text.setEnabled(false);
            Green_text.setEnabled(false);
            Black_text.setEnabled(false);
            Red_text.setSelected(false);
            Green_text.setSelected(false);
            Black_text.setSelected(false);
            Text_2.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_Color_textActionPerformed

    private void Red_fondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Red_fondActionPerformed

        Green_fond.setSelected(false);
        Blue_fond.setSelected(false);
        if (Red_fond.isSelected()) {
            Text_2.setBackground(Color.red);
            Text_2.setOpaque(true);
        } else {
            Text_2.setOpaque(false);
        }


    }//GEN-LAST:event_Red_fondActionPerformed

    private void Panel_casseAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Panel_casseAncestorAdded
        Panel_casse.setEnabled(false);
        Maj.setEnabled(false);
        Min.setEnabled(false);
    }//GEN-LAST:event_Panel_casseAncestorAdded

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
        jPanel2.setEnabled(false);
        jPanel1.setEnabled(false);
        Green_text.setEnabled(false);
        Black_text.setEnabled(false);
        Red_text.setEnabled(false);
    }//GEN-LAST:event_jPanel2AncestorAdded

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
        jPanel1.setEnabled(false);
        Green_fond.setEnabled(false);
        Blue_fond.setEnabled(false);
        Red_fond.setEnabled(false);
    }//GEN-LAST:event_jPanel1AncestorAdded

    private void Green_fondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Green_fondActionPerformed
        Red_fond.setSelected(false);
        Blue_fond.setSelected(false);
        if (Green_fond.isSelected()) {
            Text_2.setBackground(Color.green);
            Text_2.setOpaque(true);
        } else {
            Text_2.setOpaque(false);
        }
    }//GEN-LAST:event_Green_fondActionPerformed

    private void Green_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Green_textActionPerformed
        Red_text.setSelected(false);
        Black_text.setSelected(false);
        Text_2.setForeground(new Color(34, 139, 34));

    }//GEN-LAST:event_Green_textActionPerformed

    private void Choice_panelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Choice_panelAncestorAdded
        Choice_panel.setEnabled(false);
        Color_font.setEnabled(false);
        Color_text.setEnabled(false);
        Casse.setEnabled(false);
    }//GEN-LAST:event_Choice_panelAncestorAdded

    private void Blue_fondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blue_fondActionPerformed
        // Désactive les autres boutons radio
        Red_fond.setSelected(false);
        Green_fond.setSelected(false);
        if (Blue_fond.isSelected()) {
            Text_2.setBackground(Color.blue);
            Text_2.setOpaque(true);
        } else {
            Text_2.setOpaque(false);
        }

    }//GEN-LAST:event_Blue_fondActionPerformed

    private void Red_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Red_textActionPerformed
        // Désactive les autres boutons radio
        Green_text.setSelected(false);
        Black_text.setSelected(false);
        Text_2.setForeground(new Color(255, 0, 0));
 
    }//GEN-LAST:event_Red_textActionPerformed

    private void Black_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Black_textActionPerformed
        // Désactive les autres boutons radio
        Green_text.setSelected(false);
        Red_text.setSelected(false);
        Text_2.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_Black_textActionPerformed

    private void Text_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_1KeyReleased

        result = Text_1.getText();
        Text_2.setText(result);
        if (result.length() > 0) {
            Choice_panel.setEnabled(true);
            Color_font.setEnabled(true);
            Color_text.setEnabled(true);
            Casse.setEnabled(true);
        } else {
            
            Color_font.setSelected(false);
//            Choice_panel.setEnabled(false);
//            Color_font.setSelected(false);
//            Color_text.setSelected(false);
//
//            Casse.setSelected(false);
//            Color_font.setEnabled(false);
//            Color_text.setEnabled(false);
//            Casse.setEnabled(false);
//
//            jPanel2.setEnabled(false);
//            Red_text.setEnabled(false);
//            Green_text.setEnabled(false);
//            Black_text.setEnabled(false);
//            Red_text.setSelected(false);
//            Green_text.setSelected(false);
//            Black_text.setSelected(false);
//
//            jPanel1.setEnabled(false);
//            Green_fond.setEnabled(false);
//            Blue_fond.setEnabled(false);
//            Red_fond.setEnabled(false);
//            Green_fond.setSelected(false);
//            Blue_fond.setSelected(false);
//            Red_fond.setSelected(false);
//
//            Panel_casse.setEnabled(false);
//            Maj.setEnabled(false);
//            Min.setEnabled(false);
//            Maj.setSelected(false);
//            Min.setSelected(false);
//            Text_2.setOpaque(false);
//            Text_2.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_Text_1KeyReleased

    private void Color_fontStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Color_fontStateChanged
        // TODO add your handling code here:
        if (Color_font.isSelected()) {
            jPanel1.setEnabled(true);
            Red_fond.setEnabled(true);
            Green_fond.setEnabled(true);
            Blue_fond.setEnabled(true);
        } else {
            jPanel1.setEnabled(false);
            Red_fond.setEnabled(false);
            Green_fond.setEnabled(false);
            Blue_fond.setEnabled(false);
            jPanel1.setEnabled(false);
            Green_fond.setEnabled(false);
            Blue_fond.setEnabled(false);
            Red_fond.setEnabled(false);
            Green_fond.setSelected(false);
            Blue_fond.setSelected(false);
            Red_fond.setSelected(false);
            Text_2.setOpaque(false);
        }
    }//GEN-LAST:event_Color_fontStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Black_text;
    private javax.swing.JRadioButton Blue_fond;
    private javax.swing.JCheckBox Casse;
    private javax.swing.JPanel Choice_panel;
    private javax.swing.JCheckBox Color_font;
    private javax.swing.JCheckBox Color_text;
    private javax.swing.JRadioButton Green_fond;
    private javax.swing.JRadioButton Green_text;
    private javax.swing.JRadioButton Maj;
    private javax.swing.JRadioButton Min;
    private javax.swing.JPanel Panel_casse;
    private javax.swing.JRadioButton Red_fond;
    private javax.swing.JRadioButton Red_text;
    private javax.swing.JTextPane Text_1;
    private javax.swing.JLabel Text_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
