/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package developpement_swing;

import java.awt.Color;

/**
 *
 * @author 80010-37-15
 */
public class Slider extends javax.swing.JFrame {

    int value_red;
    int value_green;
    int value_blue;

    /**
     * Creates new form Slider
     */
    public Slider() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_main = new javax.swing.JPanel();
        Panel_second = new javax.swing.JPanel();
        Red = new javax.swing.JLabel();
        Green = new javax.swing.JLabel();
        Blue = new javax.swing.JLabel();
        Slider_red = new javax.swing.JSlider();
        Slider_green = new javax.swing.JSlider();
        Slider_blue = new javax.swing.JSlider();
        Panel_red = new javax.swing.JPanel();
        Panel_green = new javax.swing.JPanel();
        Panel_blue = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_main.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Panel_mainAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Panel_main.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Panel_mainPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout Panel_mainLayout = new javax.swing.GroupLayout(Panel_main);
        Panel_main.setLayout(Panel_mainLayout);
        Panel_mainLayout.setHorizontalGroup(
            Panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Panel_mainLayout.setVerticalGroup(
            Panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        Red.setText("Rouge");

        Green.setText("Vert");

        Blue.setText("Blue");

        Slider_red.setMaximum(255);
        Slider_red.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Slider_redStateChanged(evt);
            }
        });

        Slider_green.setMaximum(255);
        Slider_green.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Slider_greenStateChanged(evt);
            }
        });

        Slider_blue.setMaximum(255);
        Slider_blue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Slider_blueStateChanged(evt);
            }
        });

        javax.swing.GroupLayout Panel_secondLayout = new javax.swing.GroupLayout(Panel_second);
        Panel_second.setLayout(Panel_secondLayout);
        Panel_secondLayout.setHorizontalGroup(
            Panel_secondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_secondLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Panel_secondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Red)
                    .addComponent(Green)
                    .addComponent(Blue))
                .addGap(18, 18, 18)
                .addGroup(Panel_secondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Slider_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slider_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slider_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_secondLayout.setVerticalGroup(
            Panel_secondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_secondLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(Panel_secondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Red)
                    .addComponent(Slider_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_secondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Green)
                    .addComponent(Slider_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_secondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Blue)
                    .addComponent(Slider_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Panel_red.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout Panel_redLayout = new javax.swing.GroupLayout(Panel_red);
        Panel_red.setLayout(Panel_redLayout);
        Panel_redLayout.setHorizontalGroup(
            Panel_redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        Panel_redLayout.setVerticalGroup(
            Panel_redLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        Panel_green.setBackground(new java.awt.Color(0, 128, 0));

        javax.swing.GroupLayout Panel_greenLayout = new javax.swing.GroupLayout(Panel_green);
        Panel_green.setLayout(Panel_greenLayout);
        Panel_greenLayout.setHorizontalGroup(
            Panel_greenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        Panel_greenLayout.setVerticalGroup(
            Panel_greenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        Panel_blue.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout Panel_blueLayout = new javax.swing.GroupLayout(Panel_blue);
        Panel_blue.setLayout(Panel_blueLayout);
        Panel_blueLayout.setHorizontalGroup(
            Panel_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Panel_blueLayout.setVerticalGroup(
            Panel_blueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Panel_second, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Panel_red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Panel_green, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Panel_blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addComponent(Panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_second, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(Panel_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Panel_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Panel_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void Slider_redStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Slider_redStateChanged
        change(evt);
        
    }//GEN-LAST:event_Slider_redStateChanged

    private void Slider_greenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Slider_greenStateChanged
        change(evt);
         
    }//GEN-LAST:event_Slider_greenStateChanged

    private void Slider_blueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Slider_blueStateChanged
        change(evt);
         
    }//GEN-LAST:event_Slider_blueStateChanged

    private void change(javax.swing.event.ChangeEvent evt) {                                         
        if (evt.getSource() == Slider_blue) {
            value_blue = Slider_blue.getValue();
        }
        if (evt.getSource() == Slider_green) {
            value_green = Slider_green.getValue();
        }
        if (evt.getSource() == Slider_red) {
            value_red = Slider_red.getValue();
        }
        Panel_main.setBackground(new Color(value_red, value_green, value_blue));
         
    }
    
    private void Panel_mainAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Panel_mainAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_mainAncestorAdded

    private void Panel_mainPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Panel_mainPropertyChange
        // TODO add your handling code here:
           System.out.println("change ...");
           System.out.println(evt.getPropertyName());
    }//GEN-LAST:event_Panel_mainPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Slider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Blue;
    private javax.swing.JLabel Green;
    private javax.swing.JPanel Panel_blue;
    private javax.swing.JPanel Panel_green;
    private javax.swing.JPanel Panel_main;
    private javax.swing.JPanel Panel_red;
    private javax.swing.JPanel Panel_second;
    private javax.swing.JLabel Red;
    private javax.swing.JSlider Slider_blue;
    private javax.swing.JSlider Slider_green;
    private javax.swing.JSlider Slider_red;
    // End of variables declaration//GEN-END:variables
}
